var challenge = "30 Days Of JavaScript";
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toUpperCase());
console.log(challenge.toLowerCase());
console.log(challenge.substring(0,2));
console.log(challenge.substring(11));
console.log(challenge.includes("Script"));
console.log(challenge.split(""));
console.log(challenge.split(" "));
console.log('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(","));
console.log(challenge.replace("JavaScript","Python"));
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt("J"));
console.log(challenge.indexOf("a"));
console.log(challenge.lastIndexOf("a"));
var line = "You cannot end a sentence with because because because is a conjunction";
console.log(line.indexOf("because"));
console.log(line.lastIndexOf("because"));
console.log(line.search("because"));
console.log(" 30 days of JavaScript ".trim());
console.log(challenge.startsWith("3"));
console.log(challenge.endsWith("t"));
console.log(challenge.match("a"));
console.log("30 Days of ".concat("JavaScript"));
console.log(challenge.repeat(2));